name: Action

on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout git repo
        uses: actions/checkout@v4
        with:
          path: ./repo
          fetch-depth: 0

      - name: Set up Golang
        uses: actions/setup-go@v5
        with:
          go-version: 'stable'

      - name: Install dependencies
        run: |
          go version && go env && export PATH=$PATH:$(go env GOPATH)/bin
          go install golang.org/dl/go1.20.14@latest && go1.20.14 download && go1.20.14 version
          sudo apt-get update
          sudo apt-get -y install gcc-mingw-w64-x86-64
          sudo apt-get -y install gcc-arm-linux-gnueabihf libc6-dev-armhf-cross
          sudo apt-get -y install gcc-aarch64-linux-gnu libc6-dev-arm64-cross
          wget https://dl.google.com/android/repository/android-ndk-r26b-linux.zip && unzip android-ndk-r26b-linux.zip && rm android-ndk-r26b-linux.zip

      # - name: Fetch zTool
      #   run: wget "https://r2eu.zxwy.link/gh/lx-source/statics/ztool-20240323.zip" -O ../ztool.zip && cd ../ && unzip ztool.zip
      #   continue-on-error: true

      - name: Run Action
        run: go run repo/action.go

      - name: Short SHA
        uses: benjlevesque/short-sha@v2.2
        id: short-sha

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: lx-source-bin_${{ env.SHA }}
          path: ./dist
